language: node_js
node_js: "10"
install:
  - npm install
script:
  - npm test
after_success:
  - sudo apt-get update
  - sudo apt-get install sshpass
  - sshpass -p $EC2_PASSWORD ssh cd@$EC2_IP
  - scp -rp . cd@$EC2_IP:/opt/application -o StrictHostKeyChecking=no